// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/bug/ent/companyaddress"
	"entgo.io/bug/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CompanyAddressDelete is the builder for deleting a CompanyAddress entity.
type CompanyAddressDelete struct {
	config
	hooks    []Hook
	mutation *CompanyAddressMutation
}

// Where appends a list predicates to the CompanyAddressDelete builder.
func (cad *CompanyAddressDelete) Where(ps ...predicate.CompanyAddress) *CompanyAddressDelete {
	cad.mutation.Where(ps...)
	return cad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cad *CompanyAddressDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, cad.sqlExec, cad.mutation, cad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (cad *CompanyAddressDelete) ExecX(ctx context.Context) int {
	n, err := cad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cad *CompanyAddressDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(companyaddress.Table, sqlgraph.NewFieldSpec(companyaddress.FieldID, field.TypeInt))
	if ps := cad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, cad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	cad.mutation.done = true
	return affected, err
}

// CompanyAddressDeleteOne is the builder for deleting a single CompanyAddress entity.
type CompanyAddressDeleteOne struct {
	cad *CompanyAddressDelete
}

// Where appends a list predicates to the CompanyAddressDelete builder.
func (cado *CompanyAddressDeleteOne) Where(ps ...predicate.CompanyAddress) *CompanyAddressDeleteOne {
	cado.cad.mutation.Where(ps...)
	return cado
}

// Exec executes the deletion query.
func (cado *CompanyAddressDeleteOne) Exec(ctx context.Context) error {
	n, err := cado.cad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{companyaddress.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cado *CompanyAddressDeleteOne) ExecX(ctx context.Context) {
	if err := cado.Exec(ctx); err != nil {
		panic(err)
	}
}
