// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/bug/ent/employeeaddress"
	"entgo.io/bug/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EmployeeAddressDelete is the builder for deleting a EmployeeAddress entity.
type EmployeeAddressDelete struct {
	config
	hooks    []Hook
	mutation *EmployeeAddressMutation
}

// Where appends a list predicates to the EmployeeAddressDelete builder.
func (ead *EmployeeAddressDelete) Where(ps ...predicate.EmployeeAddress) *EmployeeAddressDelete {
	ead.mutation.Where(ps...)
	return ead
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ead *EmployeeAddressDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ead.sqlExec, ead.mutation, ead.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ead *EmployeeAddressDelete) ExecX(ctx context.Context) int {
	n, err := ead.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ead *EmployeeAddressDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(employeeaddress.Table, sqlgraph.NewFieldSpec(employeeaddress.FieldID, field.TypeInt))
	if ps := ead.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ead.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ead.mutation.done = true
	return affected, err
}

// EmployeeAddressDeleteOne is the builder for deleting a single EmployeeAddress entity.
type EmployeeAddressDeleteOne struct {
	ead *EmployeeAddressDelete
}

// Where appends a list predicates to the EmployeeAddressDelete builder.
func (eado *EmployeeAddressDeleteOne) Where(ps ...predicate.EmployeeAddress) *EmployeeAddressDeleteOne {
	eado.ead.mutation.Where(ps...)
	return eado
}

// Exec executes the deletion query.
func (eado *EmployeeAddressDeleteOne) Exec(ctx context.Context) error {
	n, err := eado.ead.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{employeeaddress.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (eado *EmployeeAddressDeleteOne) ExecX(ctx context.Context) {
	if err := eado.Exec(ctx); err != nil {
		panic(err)
	}
}
