// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Address is the predicate function for address builders.
type Address func(*sql.Selector)

// Company is the predicate function for company builders.
type Company func(*sql.Selector)

// CompanyAddress is the predicate function for companyaddress builders.
type CompanyAddress func(*sql.Selector)

// Employee is the predicate function for employee builders.
type Employee func(*sql.Selector)

// EmployeeAddress is the predicate function for employeeaddress builders.
type EmployeeAddress func(*sql.Selector)
